// Auto-generated file. Do not modify.
package com.frisboo.corebanking.convention

public object CatalogVersionConstants {

    public object Versions {
        public const val ARROWKT_VERSION: String = "arrowkt.version"
        public const val CPD_VERSION: String = "cpd.version"
        public const val DEPENDENCY_ANALYSIS_VERSION: String = "dependency.analysis.version"
        public const val DETEKT_VERSION: String = "detekt.version"
        public const val DOKKA_VERSION: String = "dokka.version"
        public const val EXPOSED_VERSION: String = "exposed.version"
        public const val FRISBOO_COREBANKING_VERSION: String = "frisboo.corebanking.version"
        public const val FRISBOO_OPENAPI_CONVENTION_VERSION: String = "frisboo.openapi.convention.version"
        public const val GRADLE_VERSIONS_VERSION: String = "gradle.versions.version"
        public const val GRPC_KOTLIN_STUB_VERSION: String = "grpc.kotlin.stub.version"
        public const val GRPC_PROTOBUF_VERSION: String = "grpc.protobuf.version"
        public const val H2_VERSION: String = "h2.version"
        public const val JACKSON_VERSION: String = "jackson.version"
        public const val JETBRAINS_ANNOTATIONS_VERSION: String = "jetbrains.annotations.version"
        public const val JGIT_VERSION: String = "jgit.version"
        public const val JUNIT_VERSION: String = "junit.version"
        public const val JVM_TARGET_VERSION: String = "jvm.target.version"
        public const val KOTEST_VERSION: String = "kotest.version"
        public const val KOTLIN_LANGUAGE_VERSION: String = "kotlin.language.version"
        public const val KOTLIN_LOGGING_VERSION: String = "kotlin.logging.version"
        public const val KOTLIN_VERSION: String = "kotlin.version"
        public const val KOTLINX_COROUTINES_VERSION: String = "kotlinx.coroutines.version"
        public const val KOVER_VERSION: String = "kover.version"
        public const val KTLINT_VERSION: String = "ktlint.version"
        public const val MAVEN_PUBLISH_VERSION: String = "maven.publish.version"
        public const val MOCKK_VERSION: String = "mockk.version"
        public const val MONGODB_VERSION: String = "mongodb.version"
        public const val OPENAPI_GENERATOR_VERSION: String = "openapi.generator.version"
        public const val OWASPCHECK_VERSION: String = "owaspCheck.version"
        public const val PLUGIN_PUBLISH_VERSION: String = "plugin.publish.version"
        public const val POSTGRESQL_VERSION: String = "postgresql.version"
        public const val PROTOBUF_PLUGIN_VERSION: String = "protobuf.plugin.version"
        public const val PROTOBUF_VERSION: String = "protobuf.version"
        public const val REACTOR_VERSION: String = "reactor.version"
        public const val RESTRICT_IMPORTS_VERSION: String = "restrict.imports.version"
        public const val SPOTLESS_VERSION: String = "spotless.version"
        public const val SPRING_BOOT_VERSION: String = "spring.boot.version"
        public const val SPRING_DEPENDENCY_MANAGEMENT_VERSION: String = "spring.dependency.management.version"
        public const val SPRING_GRPC_VERSION: String = "spring.grpc.version"
        public const val SPRINGDOC_OPENAPI_PLUGIN_VERSION: String = "springdoc.openapi.plugin.version"
        public const val SPRINGDOC_OPENAPI_VERSION: String = "springdoc.openapi.version"
        public const val TEST_RETRY_VERSION: String = "test.retry.version"
        public const val TESTCONTAINERS_VERSION: String = "testcontainers.version"
    }

    public object Plugins {
        public const val CPD: String = "cpd"
        public const val DEPENDENCY_ANALYSIS: String = "dependency.analysis"
        public const val DETEKT: String = "detekt"
        public const val DOKKA: String = "dokka"
        public const val FRISBOO_COREBANKING_CONVENTION: String = "frisboo.corebanking.convention"
        public const val FRISBOO_COREBANKING_GRPC_CONVENTION: String = "frisboo.corebanking.grpc.convention"
        public const val FRISBOO_COREBANKING_MESSAGING_CONVENTION: String = "frisboo.corebanking.messaging.convention"
        public const val FRISBOO_COREBANKING_OPENAPI_CONVENTION: String = "frisboo.corebanking.openapi.convention"
        public const val FRISBOO_COREBANKING_PERSISTENCE_CONVENTION: String = "frisboo.corebanking.persistence.convention"
        public const val FRISBOO_COREBANKING_QUALITY_CONVENTION: String = "frisboo.corebanking.quality.convention"
        public const val FRISBOO_COREBANKING_SPRINGBOOT_CONVENTION: String = "frisboo.corebanking.springboot.convention"
        public const val FRISBOO_COREBANKING_TELEMETRY_CONVENTION: String = "frisboo.corebanking.telemetry.convention"
        public const val GRADLE_VERSIONS: String = "gradle.versions"
        public const val KOTLIN_JVM: String = "kotlin.jvm"
        public const val KOTLIN_SPRING: String = "kotlin.spring"
        public const val KOVER: String = "kover"
        public const val MAVEN_PUBLISH: String = "maven.publish"
        public const val OPENAPI_GENERATOR: String = "openapi.generator"
        public const val PLUGIN_PUBLISH: String = "plugin.publish"
        public const val PROTOBUF: String = "protobuf"
        public const val SPOTLESS: String = "spotless"
        public const val SPRING_BOOT: String = "spring.boot"
        public const val SPRING_DEPENDENCY_MANAGEMENT: String = "spring.dependency.management"
        public const val SPRINGDOC_OPENAPI: String = "springdoc.openapi"
        public const val TEST_RETRY: String = "test.retry"
    }

    public object Libraries {
        public const val ARROW_KT_BOM: String = "arrow.kt.bom"
        public const val ARROW_KT_CORE: String = "arrow.kt.core"
        public const val ARROW_KT_COROUTINES: String = "arrow.kt.coroutines"
        public const val COREBANKING_CORE: String = "corebanking.core"
        public const val COREBANKING_HTTP: String = "corebanking.http"
        public const val COREBANKING_SPRING_BOOT: String = "corebanking.spring.boot"
        public const val COREBANKING_TRANSACTION: String = "corebanking.transaction"
        public const val COREBANKING_VERSION: String = "corebanking.version"
        public const val DETEKT_GRADLE_PLUGIN: String = "detekt.gradle.plugin"
        public const val EXPOSED_BOM: String = "exposed.bom"
        public const val EXPOSED_KOTLIN_DATETIME: String = "exposed.kotlin.datetime"
        public const val EXPOSED_R2DBC: String = "exposed.r2dbc"
        public const val EXPOSED_SPRING_BOOT_STARTER: String = "exposed.spring.boot.starter"
        public const val FRISBOO_COREBANKING_BOM: String = "frisboo.corebanking.bom"
        public const val GRPC_KOTLIN_STUB: String = "grpc.kotlin.stub"
        public const val GRPC_NETTY_SHADED: String = "grpc.netty.shaded"
        public const val GRPC_PROTOBUF: String = "grpc.protobuf"
        public const val H2: String = "h2"
        public const val JACKSON_BOM: String = "jackson.bom"
        public const val JACKSON_MODULE_KOTLIN: String = "jackson.module.kotlin"
        public const val JETBRAINS_ANNOTATIONS: String = "jetbrains.annotations"
        public const val JGIT_GRADLE_PLUGIN: String = "jgit.gradle.plugin"
        public const val JUNIT_BOM: String = "junit.bom"
        public const val JUNIT_PLATFORM_LAUNCHER: String = "junit.platform.launcher"
        public const val KOTEST_ASSERTIONS_CORE: String = "kotest.assertions.core"
        public const val KOTEST_RUNNER_JUNIT5: String = "kotest.runner.junit5"
        public const val KOTLIN_BOM: String = "kotlin.bom"
        public const val KOTLIN_GRADLE_PLUGIN: String = "kotlin.gradle.plugin"
        public const val KOTLIN_LOGGING: String = "kotlin.logging"
        public const val KOTLIN_REFLECT: String = "kotlin.reflect"
        public const val KOTLIN_TEST_JUNIT5: String = "kotlin.test.junit5"
        public const val KOTLINX_COROUTINES_BOM: String = "kotlinx.coroutines.bom"
        public const val KOTLINX_COROUTINES_CORE: String = "kotlinx.coroutines.core"
        public const val KOTLINX_COROUTINES_REACTOR: String = "kotlinx.coroutines.reactor"
        public const val KOTLINX_COROUTINES_TEST: String = "kotlinx.coroutines.test"
        public const val KOVER_GRADLE_PLUGIN: String = "kover.gradle.plugin"
        public const val MOCKK: String = "mockk"
        public const val MONGODB: String = "mongodb"
        public const val OWASP_DEPCHECK_GRADLE_PLUGIN: String = "owasp.depcheck.gradle.plugin"
        public const val POSTGRESQL: String = "postgresql"
        public const val PROTOBUF_KOTLIN: String = "protobuf.kotlin"
        public const val REACTOR_BOM: String = "reactor.bom"
        public const val REACTOR_KOTLIN_EXTENSIONS: String = "reactor.kotlin.extensions"
        public const val REACTOR_TEST: String = "reactor.test"
        public const val RESTRICT_IMPORTS_PLUGIN: String = "restrict.imports.plugin"
        public const val SPOTLESS_GRADLE_PLUGIN: String = "spotless.gradle.plugin"
        public const val SPRING_BOOT_BOM: String = "spring.boot.bom"
        public const val SPRING_BOOT_CONFIGURATION_PROCESSOR: String = "spring.boot.configuration.processor"
        public const val SPRING_BOOT_DEVTOOLS: String = "spring.boot.devtools"
        public const val SPRING_BOOT_SECURITY_TEST: String = "spring.boot.security.test"
        public const val SPRING_BOOT_STARTER_ACTUATOR: String = "spring.boot.starter.actuator"
        public const val SPRING_BOOT_STARTER_DATA_MONGODB: String = "spring.boot.starter.data.mongodb"
        public const val SPRING_BOOT_STARTER_HATEOAS: String = "spring.boot.starter.hateoas"
        public const val SPRING_BOOT_STARTER_TEST: String = "spring.boot.starter.test"
        public const val SPRING_BOOT_STARTER_VALIDATION: String = "spring.boot.starter.validation"
        public const val SPRING_BOOT_STARTER_WEBFLUX: String = "spring.boot.starter.webflux"
        public const val SPRING_GRPC_STARTER: String = "spring.grpc.starter"
        public const val SPRINGDOC_OPENAPI_BOM: String = "springdoc.openapi.bom"
        public const val SPRINGDOC_OPENAPI_STARTER_WEBFLUX_API: String = "springdoc.openapi.starter.webflux.api"
        public const val SPRINGDOC_OPENAPI_STARTER_WEBFLUX_UI: String = "springdoc.openapi.starter.webflux.ui"
        public const val TESTCONTAINERS_BOM: String = "testcontainers.bom"
        public const val TESTCONTAINERS_JUNIT_JUPITER: String = "testcontainers.junit.jupiter"
        public const val TESTCONTAINERS_MONGODB: String = "testcontainers.mongodb"
        public const val TESTCONTAINERS_POSTGRESQL: String = "testcontainers.postgresql"
    }

    public object Bundles {

    }
}
