POM_ARTIFACT_ID=version-catalog
POM_NAME=Frisboo Corebanking Version Catalog
POM_DESCRIPTION=Version Catalog for Frisboo Corebanking
POM_INCEPTION_YEAR=2025
POM_URL=
POM_LICENSE_NAME=The Apache Software License, Version 2.0
POM_LICENSE_URL=https://www.apache.org/licenses/LICENSE-2.0.txt
POM_LICENSE_DIST=repo
POM_SCM_URL=
POM_SCM_CONNECTION=
POM_SCM_DEV_CONNECTION=
POM_DEVELOPER_ID=frisboo
POM_DEVELOPER_NAME=Frisboo Limited
POM_DEVELOPER_URL=
mavenCentralPublishing=false
signAllPublications=false
mavenCentralAutomaticPublishing=false
