[versions]
arrowkt-version = "2.1.0"
cpd-version = "3.5"
dependency-analysis-version = "3.1.0"
detekt-version = "1.23.8"
dokka-version = "2.1.0"
exposed-version = "1.0.0-rc-2"
frisboo-corebanking-version = "0.0.1"
frisboo-openapi-convention-version = "0.0.1"
gradle-versions-version = "0.53.0"
grpc-kotlin-stub-version = "1.5.0"
grpc-protobuf-version = "1.76.0"
h2-version = "2.4.240"
jackson-version = "2.20.0"
jetbrains-annotations-version = "26.0.2-1"
jgit-version = "7.4.0.202509020913-r"
junit-version = "6.0.0"
jvm-target-version = "24"
kotest-version = "6.0.4"
kotlin-language-version = "2.2"
kotlin-logging-version = "7.0.13"
kotlin-version = "2.2.21"
kotlinx-coroutines-version = "1.10.2"
kover-version = "0.9.3"
ktlint-version = "1.7.1"
maven-publish-version = "0.34.0"
mockk-version = "1.14.6"
mongodb-version = "5.6.1"
openapi-generator-version = "7.14.0"
owaspCheck-version = "12.1.8"
plugin-publish-version = "2.0.0"
postgresql-version = "42.7.8"
protobuf-plugin-version = "0.9.5"
protobuf-version = "3.25.3"
reactor-version = "2024.0.11"
restrict-imports-version = "3.0.0"
spotless-version = "8.0.0"
spring-boot-version = "3.5.6"
spring-dependency-management-version = "1.1.7"
spring-grpc-version = "0.11.0"
springdoc-openapi-plugin-version = "1.9.0"
springdoc-openapi-version = "2.8.13"
test-retry-version = "1.6.4"
testcontainers-version = "2.0.1"

[libraries]
arrow-kt-bom = { module = "io.arrow-kt:arrow-stack", version.ref = "arrowkt-version" }
arrow-kt-core = { module = "io.arrow-kt:arrow-core" }
arrow-kt-coroutines = { module = "io.arrow-kt:arrow-fx-coroutines" }
corebanking-core = { module = "com.frisboo.corebanking:frisboo-core" }
corebanking-http = { module = "com.frisboo.corebanking:frisboo-http" }
corebanking-spring-boot = { module = "com.frisboo.corebanking:frisboo-spring-boot" }
corebanking-transaction = { module = "com.frisboo.corebanking:frisboo-transaction" }
corebanking-version = { module = "com.frisboo.corebanking:version-catalog", version.ref = "frisboo-corebanking-version" }
detekt-gradle-plugin = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt-version" }
exposed-bom = { module = "org.jetbrains.exposed:exposed-bom", version.ref = "exposed-version" }
exposed-kotlin-datetime = { module = "org.jetbrains.exposed:exposed-kotlin-datetime" }
exposed-r2dbc = { module = "org.jetbrains.exposed:exposed-r2dbc" }
exposed-spring-boot-starter = { module = "org.jetbrains.exposed:exposed-spring-boot-starter" }
frisboo-corebanking-bom = { module = "com.frisboo.corebanking:frisboo-bom", version.ref = "frisboo-corebanking-version" }
grpc-kotlin-stub = { module = "io.grpc:grpc-kotlin-stub", version.ref = "grpc-kotlin-stub-version" }
grpc-netty-shaded = { module = "io.grpc:grpc-netty-shaded", version.ref = "grpc-protobuf-version" }
grpc-protobuf = { module = "io.grpc:grpc-protobuf", version.ref = "grpc-protobuf-version" }
h2 = { module = "com.h2database:h2", version.ref = "h2-version" }
jackson-bom = { module = "com.fasterxml.jackson:jackson-bom", version.ref = "jackson-version" }
jackson-module-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin" }
jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrains-annotations-version" }
jgit-gradle-plugin = { module = "org.eclipse.jgit:org.eclipse.jgit", version.ref = "jgit-version" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit-version" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest-version" }
kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest-version" }
kotlin-bom = { module = "org.jetbrains.kotlin:kotlin-bom", version.ref = "kotlin-version" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin" }
kotlin-logging = { module = "io.github.oshai:kotlin-logging-jvm", version.ref = "kotlin-logging-version" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect" }
kotlin-test-junit5 = { module = "org.jetbrains.kotlin:kotlin-test-junit5" }
kotlinx-coroutines-bom = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-bom", version.ref = "kotlinx-coroutines-version" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core" }
kotlinx-coroutines-reactor = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-reactor" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test" }
kover-gradle-plugin = { module = "org.jetbrains.kotlinx:kover-gradle-plugin", version.ref = "kover-version" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk-version" }
mongodb = { module = "org.mongodb:mongodb-driver-kotlin-coroutine" }
owasp-depcheck-gradle-plugin = { module = "org.owasp:dependency-check-gradle", version.ref = "owaspCheck-version" }
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql-version" }
protobuf-kotlin = { module = "com.google.protobuf:protobuf-kotlin", version.ref = "protobuf-version" }
reactor-bom = { module = "io.projectreactor:reactor-bom", version.ref = "reactor-version" }
reactor-kotlin-extensions = { module = "io.projectreactor.kotlin:reactor-kotlin-extensions" }
reactor-test = { module = "io.projectreactor:reactor-test" }
restrict-imports-plugin = { module = "de.skuzzle.restrictimports:de.skuzzle.restrictimports.gradle.plugin", version.ref = "restrict-imports-version" }
spotless-gradle-plugin = { module = "com.diffplug.spotless:com.diffplug.spotless.gradle.plugin", version.ref = "spotless-version" }
spring-boot-bom = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "spring-boot-version" }
spring-boot-configuration-processor = { module = "org.springframework.boot:spring-boot-configuration-processor" }
spring-boot-devtools = { module = "org.springframework.boot:spring-boot-devtools" }
spring-boot-security-test = { module = "org.springframework.security:spring-security-test" }
spring-boot-starter-actuator = { module = "org.springframework.boot:spring-boot-starter-actuator" }
spring-boot-starter-data-mongodb = { module = "org.springframework.boot:spring-boot-starter-data-mongodb" }
spring-boot-starter-hateoas = { module = "org.springframework.boot:spring-boot-starter-hateoas" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }
spring-boot-starter-validation = { module = "org.springframework.boot:spring-boot-starter-validation" }
spring-boot-starter-webflux = { module = "org.springframework.boot:spring-boot-starter-webflux" }
spring-grpc-starter = { module = "org.springframework.grpc:spring-grpc-spring-boot-starter" }
springdoc-openapi-bom = { module = "org.springdoc:springdoc-openapi-bom", version.ref = "springdoc-openapi-version" }
springdoc-openapi-starter-webflux-api = { module = "org.springdoc:springdoc-openapi-starter-webflux-api" }
springdoc-openapi-starter-webflux-ui = { module = "org.springdoc:springdoc-openapi-starter-webflux-ui" }
testcontainers-bom = { module = "org.testcontainers:testcontainers-bom", version.ref = "testcontainers-version" }
testcontainers-junit-jupiter = { module = "org.testcontainers:junit-jupiter" }
testcontainers-mongodb = { module = "org.testcontainers:mongodb" }
testcontainers-postgresql = { module = "org.testcontainers:postgresql" }

[plugins]
cpd = { id = "de.aaschmid.cpd", version.ref = "cpd-version" }
dependency-analysis = { id = "com.autonomousapps.dependency-analysis", version.ref = "dependency-analysis-version" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt-version" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka-version" }
frisboo-corebanking-convention = { id = "com.frisboo.corebanking.convention", version.ref = "frisboo-corebanking-version" }
frisboo-corebanking-grpc-convention = { id = "com.frisboo.corebanking.grpc-convention", version.ref = "frisboo-corebanking-version" }
frisboo-corebanking-kotlin-convention = { id = "com.frisboo.corebanking.kotlin-convention", version.ref = "frisboo-corebanking-version" }
frisboo-corebanking-messaging-convention = { id = "com.frisboo.corebanking.messaging-convention", version.ref = "frisboo-corebanking-version" }
frisboo-corebanking-openapi-convention = { id = "com.frisboo.corebanking.openapi-convention", version.ref = "frisboo-corebanking-version" }
frisboo-corebanking-persistence-convention = { id = "com.frisboo.corebanking.persistence-convention", version.ref = "frisboo-corebanking-version" }
frisboo-corebanking-quality-convention = { id = "com.frisboo.corebanking.quality-convention", version.ref = "frisboo-corebanking-version" }
frisboo-corebanking-springboot-convention = { id = "com.frisboo.corebanking.spring-boot-convention", version.ref = "frisboo-corebanking-version" }
frisboo-corebanking-telemetry-convention = { id = "com.frisboo.corebanking.telemetry-convention", version.ref = "frisboo-corebanking-version" }
gradle-versions = { id = "com.github.ben-manes.versions", version.ref = "gradle-versions-version" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin-version" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin-version" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover-version" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "maven-publish-version" }
openapi-generator = { id = "org.openapi.generator", version.ref = "openapi-generator-version" }
plugin-publish = { id = "com.gradle.plugin-publish", version.ref = "plugin-publish-version" }
protobuf = { id = "com.google.protobuf", version.ref = "protobuf-plugin-version" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless-version" }
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot-version" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management-version" }
springdoc-openapi = { id = "org.springdoc.openapi-gradle-plugin", version.ref = "springdoc-openapi-plugin-version" }
test-retry = { id = "org.gradle.test-retry", version.ref = "test-retry-version" }
