/*
 * Copyright 2025 Frisboo Bank
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing
 * permissions and limitations under the License.
 */
package com.frisboo.corebanking.constants

public object CatalogVersionConstants {

    public object Versions {
        public const val ARROWKT: String = "arrowkt"
        public const val BUCKET4J_CORE: String = "bucket4j.core"
        public const val CAFFEINE: String = "caffeine"
        public const val CAFFEINE_COROUTINES: String = "caffeine.coroutines"
        public const val CONTEXT_PROPAGATION: String = "context.propagation"
        public const val CPD_PLUGIN: String = "cpd.plugin"
        public const val DEPENDENCY_ANALYSIS_PLUGIN: String = "dependency.analysis.plugin"
        public const val DETEKT: String = "detekt"
        public const val DETEKT_PLUGIN: String = "detekt.plugin"
        public const val DOKKA_PLUGIN: String = "dokka.plugin"
        public const val EXPOSED: String = "exposed"
        public const val FLYWAY: String = "flyway"
        public const val FLYWAY_PLUGIN: String = "flyway.plugin"
        public const val GRADLES_PLUGIN: String = "gradles.plugin"
        public const val GRPC: String = "grpc"
        public const val GRPC_KOTLIN_STUB: String = "grpc.kotlin.stub"
        public const val GRPC_NETTY_SHADED: String = "grpc.netty.shaded"
        public const val GRPC_PROTOBUF: String = "grpc.protobuf"
        public const val H2: String = "h2"
        public const val JACKSON: String = "jackson"
        public const val JACKSON_ANNOTATIONS: String = "jackson.annotations"
        public const val JACKSON_DATATYPE_JSR310: String = "jackson.datatype.jsr310"
        public const val JETBRAINS_ANNOTATIONS: String = "jetbrains.annotations"
        public const val JGIT: String = "jgit"
        public const val JUNIT: String = "junit"
        public const val JVM_TARGET: String = "jvm.target"
        public const val KOTEST: String = "kotest"
        public const val KOTEST_ASSERTIONS_ARROW: String = "kotest.assertions.arrow"
        public const val KOTEST_PROPERTY_ARBS: String = "kotest.property.arbs"
        public const val KOTEST_PROPERTY_DATETIME: String = "kotest.property.datetime"
        public const val KOTLIN: String = "kotlin"
        public const val KOTLIN_LANGUAGE: String = "kotlin.language"
        public const val KOTLIN_LOGGING: String = "kotlin.logging"
        public const val KOTLIN_PLUGIN: String = "kotlin.plugin"
        public const val KOTLINX_COROUTINES: String = "kotlinx.coroutines"
        public const val KOTLINX_DATETIME: String = "kotlinx.datetime"
        public const val KOVER: String = "kover"
        public const val KOVER_PLUGIN: String = "kover.plugin"
        public const val KTLINT: String = "ktlint"
        public const val LETTUCE: String = "lettuce"
        public const val MAVEN_PUBLISH_PLUGIN: String = "maven.publish.plugin"
        public const val MOCKK: String = "mockk"
        public const val MONGODB: String = "mongodb"
        public const val OPENAPI_GENERATOR_PLUGIN: String = "openapi.generator.plugin"
        public const val OPENTELEMETRY: String = "opentelemetry"
        public const val OWASP_DEPENDENCYCHECK_PLUGIN: String = "owasp.dependencycheck.plugin"
        public const val POSTGRESQL: String = "postgresql"
        public const val PROTOBUF: String = "protobuf"
        public const val PROTOBUF_PLUGIN: String = "protobuf.plugin"
        public const val PROTOC: String = "protoc"
        public const val PROTOC_GEN_GRPC_JAVA: String = "protoc.gen.grpc.java"
        public const val PROTOC_GEN_GRPC_KOTLIN: String = "protoc.gen.grpc.kotlin"
        public const val PROTOVALIDATE: String = "protovalidate"
        public const val REACTOR: String = "reactor"
        public const val RESILIENCE4J: String = "resilience4j"
        public const val RESTRICT_IMPORTS_PLUGIN: String = "restrict.imports.plugin"
        public const val SPOTLESS_PLUGIN: String = "spotless.plugin"
        public const val SPRING_BOOT: String = "spring.boot"
        public const val SPRING_BOOT_GRPC: String = "spring.boot.grpc"
        public const val SPRING_BOOT_PLUGIN: String = "spring.boot.plugin"
        public const val SPRING_DEPENDENCY_MANAGEMENT_PLUGIN: String = "spring.dependency.management.plugin"
        public const val SPRINGDOC_OPENAPI: String = "springdoc.openapi"
        public const val SPRINGDOC_OPENAPI_PLUGIN: String = "springdoc.openapi.plugin"
        public const val TEST_RETRY_PLUGIN: String = "test.retry.plugin"
        public const val TESTCONTAINERS: String = "testcontainers"
        public const val TESTCONTAINERS_REDIS: String = "testcontainers.redis"
        public const val TINK: String = "tink"
        public const val TOXICPROXY: String = "toxicproxy"
    }

    public object Plugins {
        public const val CPD: String = "cpd"
        public const val DEPENDENCY_ANALYSIS: String = "dependency.analysis"
        public const val DETEKT: String = "detekt"
        public const val DOKKA: String = "dokka"
        public const val FLYWAY: String = "flyway"
        public const val GRADLES: String = "gradles"
        public const val KOTLIN_JVM: String = "kotlin.jvm"
        public const val KOTLIN_SPRING: String = "kotlin.spring"
        public const val KOVER: String = "kover"
        public const val MAVEN_PUBLISH: String = "maven.publish"
        public const val OPENAPI_GENERATOR: String = "openapi.generator"
        public const val OWASP: String = "owasp"
        public const val PROTOBUF: String = "protobuf"
        public const val RESTRICTIMPORTS: String = "restrictimports"
        public const val SPOTLESS: String = "spotless"
        public const val SPRING_BOOT: String = "spring.boot"
        public const val SPRING_DEPENDENCY_MANAGEMENT: String = "spring.dependency.management"
        public const val SPRINGDOC_OPENAPI: String = "springdoc.openapi"
        public const val TEST_RETRY: String = "test.retry"
    }

    public object Libraries {
        public const val ARROW_KT_BOM: String = "arrow.kt.bom"
        public const val ARROW_KT_CORE: String = "arrow.kt.core"
        public const val ARROW_KT_COROUTINES: String = "arrow.kt.coroutines"
        public const val BUCKET4J_CORE: String = "bucket4j.core"
        public const val CAFFEINE: String = "caffeine"
        public const val CAFFEINE_COROUTINES: String = "caffeine.coroutines"
        public const val CONTEXT_PROPAGATION: String = "context.propagation"
        public const val EXPOSED_BOM: String = "exposed.bom"
        public const val EXPOSED_JSON: String = "exposed.json"
        public const val EXPOSED_KOTLIN_DATETIME: String = "exposed.kotlin.datetime"
        public const val EXPOSED_SPRING_BOOT_STARTER: String = "exposed.spring.boot.starter"
        public const val FLYWAY_CORE: String = "flyway.core"
        public const val FLYWAY_DATABASE_MONGODB: String = "flyway.database.mongodb"
        public const val FLYWAY_DATABASE_POSTGRESQL: String = "flyway.database.postgresql"
        public const val GRPC_BOM: String = "grpc.bom"
        public const val GRPC_KOTLIN_STUB: String = "grpc.kotlin.stub"
        public const val GRPC_NETTY_SHADED: String = "grpc.netty.shaded"
        public const val GRPC_PROTOBUF: String = "grpc.protobuf"
        public const val GRPC_SERVICES: String = "grpc.services"
        public const val GRPC_SERVLET: String = "grpc.servlet"
        public const val GRPC_STUB: String = "grpc.stub"
        public const val H2: String = "h2"
        public const val JACKSON_ANNOTATIONS: String = "jackson.annotations"
        public const val JACKSON_BOM: String = "jackson.bom"
        public const val JACKSON_CORE: String = "jackson.core"
        public const val JACKSON_DATABIND: String = "jackson.databind"
        public const val JACKSON_DATATYPE_JSR310: String = "jackson.datatype.jsr310"
        public const val JACKSON_MODULE_KOTLIN: String = "jackson.module.kotlin"
        public const val JETBRAINS_ANNOTATIONS: String = "jetbrains.annotations"
        public const val JGIT_GRADLE_PLUGIN: String = "jgit.gradle.plugin"
        public const val JUNIT_BOM: String = "junit.bom"
        public const val KOTEST_ASSERTIONS_ARROW: String = "kotest.assertions.arrow"
        public const val KOTEST_ASSERTIONS_CORE: String = "kotest.assertions.core"
        public const val KOTEST_BOM: String = "kotest.bom"
        public const val KOTEST_EXTENSIONS: String = "kotest.extensions"
        public const val KOTEST_EXTENSIONS_TESTCONTAINERS: String = "kotest.extensions.testcontainers"
        public const val KOTEST_PROPERTY: String = "kotest.property"
        public const val KOTEST_PROPERTY_ARBS: String = "kotest.property.arbs"
        public const val KOTEST_PROPERTY_DATETIME: String = "kotest.property.datetime"
        public const val KOTEST_RUNNER_JUNIT5: String = "kotest.runner.junit5"
        public const val KOTLIN_BOM: String = "kotlin.bom"
        public const val KOTLIN_GRADLE_PLUGIN: String = "kotlin.gradle.plugin"
        public const val KOTLIN_LOGGING: String = "kotlin.logging"
        public const val KOTLIN_REFLECT: String = "kotlin.reflect"
        public const val KOTLIN_TEST_JUNIT5: String = "kotlin.test.junit5"
        public const val KOTLINX_COROUTINES_BOM: String = "kotlinx.coroutines.bom"
        public const val KOTLINX_COROUTINES_CORE: String = "kotlinx.coroutines.core"
        public const val KOTLINX_COROUTINES_DEBUG: String = "kotlinx.coroutines.debug"
        public const val KOTLINX_COROUTINES_REACTOR: String = "kotlinx.coroutines.reactor"
        public const val KOTLINX_COROUTINES_TEST: String = "kotlinx.coroutines.test"
        public const val KOTLINX_DATETIME: String = "kotlinx.datetime"
        public const val KOVER: String = "kover"
        public const val LETTUCE_CORE: String = "lettuce.core"
        public const val MOCKK: String = "mockk"
        public const val MONGODB: String = "mongodb"
        public const val OPENTELEMETRY_BOM: String = "opentelemetry.bom"
        public const val OPENTELEMETRY_SPRING_BOOT_STARTER: String = "opentelemetry.spring.boot.starter"
        public const val POSTGRESQL: String = "postgresql"
        public const val PROTOBUF_JAVA: String = "protobuf.java"
        public const val PROTOBUF_JAVA_UTIL: String = "protobuf.java.util"
        public const val PROTOBUF_KOTLIN: String = "protobuf.kotlin"
        public const val REACTOR_BOM: String = "reactor.bom"
        public const val REACTOR_KOTLIN_EXTENSIONS: String = "reactor.kotlin.extensions"
        public const val REACTOR_TEST: String = "reactor.test"
        public const val RESILIENCE4J_BOM: String = "resilience4j.bom"
        public const val RESILIENCE4J_CIRCUITBREAKER: String = "resilience4j.circuitbreaker"
        public const val RESILIENCE4J_KOTLIN: String = "resilience4j.kotlin"
        public const val RESILIENCE4J_RATELIMITER: String = "resilience4j.ratelimiter"
        public const val SPRING_BOOT_AUTOCONFIGURE: String = "spring.boot.autoconfigure"
        public const val SPRING_BOOT_BOM: String = "spring.boot.bom"
        public const val SPRING_BOOT_CONFIGURATION_PROCESSOR: String = "spring.boot.configuration.processor"
        public const val SPRING_BOOT_DEVTOOLS: String = "spring.boot.devtools"
        public const val SPRING_BOOT_GRPC_BOM: String = "spring.boot.grpc.bom"
        public const val SPRING_BOOT_GRPC_STARTER: String = "spring.boot.grpc.starter"
        public const val SPRING_BOOT_GRPC_TEST: String = "spring.boot.grpc.test"
        public const val SPRING_BOOT_KAFKA: String = "spring.boot.kafka"
        public const val SPRING_BOOT_KAFKA_TEST: String = "spring.boot.kafka.test"
        public const val SPRING_BOOT_KOTLIN: String = "spring.boot.kotlin"
        public const val SPRING_BOOT_STARTER_ACTUATOR: String = "spring.boot.starter.actuator"
        public const val SPRING_BOOT_STARTER_CACHE: String = "spring.boot.starter.cache"
        public const val SPRING_BOOT_STARTER_DATA_MONGODB: String = "spring.boot.starter.data.mongodb"
        public const val SPRING_BOOT_STARTER_DATA_REDIS: String = "spring.boot.starter.data.redis"
        public const val SPRING_BOOT_STARTER_DATA_REDIS_REACTIVE: String = "spring.boot.starter.data.redis.reactive"
        public const val SPRING_BOOT_STARTER_DATA_REDIS_REACTIVE_TEST: String = "spring.boot.starter.data.redis.reactive.test"
        public const val SPRING_BOOT_STARTER_DATA_REDIS_TEST: String = "spring.boot.starter.data.redis.test"
        public const val SPRING_BOOT_STARTER_TEST: String = "spring.boot.starter.test"
        public const val SPRING_BOOT_STARTER_VALIDATION: String = "spring.boot.starter.validation"
        public const val SPRING_BOOT_STARTER_WEBFLUX: String = "spring.boot.starter.webflux"
        public const val SPRING_BOOT_TESTCONTAINERS: String = "spring.boot.testcontainers"
        public const val SPRINGDOC_OPENAPI_BOM: String = "springdoc.openapi.bom"
        public const val SPRINGDOC_OPENAPI_STARTER_WEBFLUX_API: String = "springdoc.openapi.starter.webflux.api"
        public const val SPRINGDOC_OPENAPI_STARTER_WEBFLUX_UI: String = "springdoc.openapi.starter.webflux.ui"
        public const val TESTCONTAINERS_BOM: String = "testcontainers.bom"
        public const val TESTCONTAINERS_H2: String = "testcontainers.h2"
        public const val TESTCONTAINERS_JUNIT_JUPITER: String = "testcontainers.junit.jupiter"
        public const val TESTCONTAINERS_KAFKA: String = "testcontainers.kafka"
        public const val TESTCONTAINERS_MONGODB: String = "testcontainers.mongodb"
        public const val TESTCONTAINERS_POSTGRESQL: String = "testcontainers.postgresql"
        public const val TESTCONTAINERS_REDIS: String = "testcontainers.redis"
        public const val TESTCONTAINERS_TOXIPROXY: String = "testcontainers.toxiproxy"
        public const val TINK: String = "tink"
        public const val TOXIPROXY: String = "toxiproxy"
    }

    public object Bundles {
        public const val SERIALIZATION: String = "serialization"
    }
}
